version: '3.8'
services:
  news-service:
    image: news-comments-service-1.0.0
    build: news-comments-service
    depends_on:
      - database-news-service
    restart: always
    environment:
      ACTIVE_PROF: prod
    ports:
      - "8080:8080"
    networks:
      - news_application_ntwrk

  database-news-service:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: news-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - news_application_ntwrk
    volumes:
      - postgres-db:/var/lib/postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - news_application_ntwrk

volumes:
  postgres-db:

networks:
  news_application_ntwrk:
