version: '3.8'
services:
  news-service:
    image: news-comments-service-1.0.0
    build:
      context: ./
      dockerfile: ./news-comments-service/Dockerfile
    depends_on:
      - database-news-service
    restart: always
    environment:
      ACTIVE_PROF: prod
    ports:
      - "8081:8080"
    networks:
      - news_application_ntwrk
    volumes:
      - logs:/var/log

  database-news-service:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: news-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - news_application_ntwrk
    volumes:
      - postgres-db:/var/lib/postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - news_application_ntwrk

  swagger-ui:
    build: swagger-ui
    image: news_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - news_application_ntwrk

  proxy:
    build: proxy
    image: news_proxy:1.0.0
    ports:
      - "8080:8080"
    networks:
      - news_application_ntwrk
    volumes:
      - proxy:/var/log/nginx

volumes:
  postgres-db:
  logs:
  proxy:

networks:
  news_application_ntwrk:
