spring:
  datasource:
    url: jdbc:postgresql://database-user-service:5432/app-user-service-db
    username: postgres
    password: postgres
  security:
    jwt:
      secret: kdc.scbhc4vdvkdc.scbhc4vdvkdc.scbhc4vdvkdc.scbhc4vdvkdc.scbhc4vdv.scbhc4vdv
  application:
    name: user-service
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 600
server:
  forward-headers-strategy: framework