spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000
  jackson:
    deserialization:
      fail-on-unknown-properties: true
exception:
  handling:
    include: true
starter:
  logger:
    include: true
management:
  endpoints:
    web:
      exposure:
        include: health, info
springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html