server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
management:
  endpoints:
    web:
      exposure:
        include: health, info