spring:
  datasource:
    url: jdbc:postgresql://database-news-service:5432/news-service-db
    username: postgres
    password: postgres
  data:
    redis:
      host: redis
      timeout: 2000
      port: 6379
  cache:
    cache-names:
      - news
      - comments
    redis:
      time-to-live: 600s
  security:
    jackson:
      deserialization:
        fail-on-unknown-properties: true
  settings:
    user-service:
      uri: http://user-service:8080/api/v1/app/users
logging:
  config: classpath:logback-prod.xml
exception:
  handling:
    include: true