spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news-service-db
    username: postgres
    password: postgres
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  settings:
    user-service:
      uri: http://localhost:8082/api/v1/app/users
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
cache:
  maxSize: 3
  algorithm: LRU
starter:
  logger:
    include: true
logging:
  config: classpath:logback-dev.xml
exception:
  handling:
    include: true
eureka:
  client:
    enabled: false