spring:
  datasource:
    url: jdbc:postgresql://database-news-service:5432/news-service-db
    username: postgres
    password: postgres
  data:
    redis:
      host: redis
      timeout: 2000
      port: 6379
  cache:
    cache-names:
      - news
      - comments
    redis:
      time-to-live: 600s