spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news-service-db
    username: postgres
    password: postgres
cache:
  maxSize: 3
  algorithm: LRU
starter:
  logger:
    include: true
logging:
  config: classpath:logback-dev.xml
exception:
  handling:
    include: true